### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by dedeTao** [bigeyechou/Rxjava2Retrofit2NetFrame#1]
Process: com.zhenggzh.dream.retrofitandrxjavademo, PID: 9173
    java.lang.ExceptionInInitializerError
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods$SingletonHolder.access$100(HttpMethods.java:142)
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods.getInstance(HttpMethods.java:149)
        at com.zhenggzh.dream.retrofitandrxjavademo.netsubscribe.MovieSubscribe.getData(MovieSubscribe.java:26)
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity.getData(MainActivity.java:61)
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity.onClickButton(MainActivity.java:35)
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity$$ViewBinder$1.doClick(MainActivity$$ViewBinder.java:18)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22295)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6337)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.IllegalArgumentException: Illegal URL: 
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:454)
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods.<init>(HttpMethods.java:136)
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods.<init>(HttpMethods.java:33)
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods$SingletonHolder.<clinit>(HttpMethods.java:143)
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods$SingletonHolder.access$100(HttpMethods.java:142) 
        at com.zhenggzh.dream.retrofitandrxjavademo.netutils.HttpMethods.getInstance(HttpMethods.java:149) 
        at com.zhenggzh.dream.retrofitandrxjavademo.netsubscribe.MovieSubscribe.getData(MovieSubscribe.java:26) 
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity.getData(MainActivity.java:61) 
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity.onClickButton(MainActivity.java:35) 
        at com.zhenggzh.dream.retrofitandrxjavademo.MainActivity$$ViewBinder$1.doClick(MainActivity$$ViewBinder.java:18) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:5619) 
        at android.view.View$PerformClick.run(View.java:22295) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6337) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by bigeyechou** [comment]
这是因为你下完代码没有配接口名，需要自己配一下
URLConstant类里面和HttpApi中 @POST("")里面
